config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do

    resources :profiles, :only => [:show, :update], :controller => "user_profiles"

    post "login" => "auth#login"
    post "logout" => "auth#logout"

    resources :chapters, :except => [:destroy, :update] do
      collection do
        get :finished
        get :unfinished
        get :weekpop
        get :mostpop
      end
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :chapters

  resources :users do
    resource :profile, :controller => "user_profiles"
  end

  resources :suggests

  resources :logs

  root 'chapters#index'

end

app/models/suggest.rb
class Suggest < ActiveRecord::Base
	validates_presence_of :topic, :content, :suggest_category
	belongs_to :user
	scope :includes_more, -> { includes( :user => :profile ) }
end

app/controllers/suggests_controller.rb
class SuggestsController < ApplicationController

	before_action :authenticate_user!, :except => [:index, :show]

	before_action :set_suggest, only: [:edit, :update, :destroy]

	def index
		@suggests = Suggest.includes_more.order("id DESC")
	end

	def show
		@suggest = Suggest.find(params[:id])
		@page_title = "故事里 - #{@suggest.topic}"
	end	

	def new
		@suggest = Suggest.new
	end

	def create
		@suggest = current_user.suggests.new(suggest_params)
		if @suggest.save
			redirect_to action: :index
		else
			render :new
		end
	end

	def edit
		@page_title = @suggest.topic
	end

	def update
		if @suggest.update(suggest_params)
			redirect_to suggests_path
		else
			render :edit
		end
	end

	def destroy
		@suggest.destroy
		redirect_to suggests_path
	end

	private

	def suggest_params
		params.require(:suggest).permit( :topic, :content, :suggest_category )
	end

	def set_suggest
		@suggest = Suggest.find(params[:id])
	end
end

app/helpers/suggests_helper.rb
module SuggestsHelper
end

app/views/suggests/_suggest_from.html.erb
<div class="form-group">
  <%= f.label :topic, "項目標題："%>
  <%= f.text_field :topic %>
</div>

<div class="form-group">
  <%= f.label :content, "項目內容："%>
  <%= f.text_area :content %>
</div>

<%= f.submit "送出", class:"btn btn-primary" %>

app/views/suggests/edit.html.erb
<h1><%= @suggest.suggest_category %></h1>

<%= form_for @suggest do |f| %>

	<%= render partial: "suggest_from", locals: { f: f } %>

<% end %>

app/views/suggests/index.html.erb
<h1>建議與錯誤回報區</h1>

	<%= link_to "我要建議", new_suggest_path(suggest_category:"我要建議"), class: "btn btn-success" %>
	<%= link_to "我要回報", new_suggest_path(suggest_category:"我要回報"), class: "btn btn-success" %>

<table class="table table-striped">
  <h2 style="text-align: center">清單列表</h2>
  <tr>
    <th>類別</th>
    <th>標題</th>
    <th>作者</th>
    <th>事項</th>
    <th>選項</th>
  </tr>
    <% @suggests.each do |s| %>
      <tr>
        <td><%= s.suggest_category %></td>
        <td><%= link_to s.topic, suggest_path(s)%></td>
        <td><%= link_to s.user.try(:display_name), user_profile_path( s.user.id ) if s.user %></td>
        <td><%= s.content %></td>
        <td>
        	<% if s.user == current_user %>
        	<%= link_to "修改",edit_suggest_path(s), class:"btn btn-success" %>
        	<%= link_to "刪除",suggest_path(s), :method => :delete, :data => { :confirm => "Are you sure?" }, class:"btn btn-danger" %>
        	<% end %>
        </td>
      </tr>
    <% end %>
</table>

app/views/suggests/new.html.erb
<h1><%= params[:suggest_category] %></h1>


<%= form_for @suggest do |f| %>
	<%= f.hidden_field :suggest_category, :value => params[:suggest_category] %>

	<%= render partial: "suggest_from", locals: { f: f } %>

<% end %>

app/views/suggests/show.html.erb
<h1><%= @suggest.topic %></h1>

<h5><%= @suggest.suggest_category %></h5>

<p><%= @suggest.content %></p>