config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do

    resources :profiles, :only => [:show, :update], :controller => "user_profiles"

    post "login" => "auth#login"
    post "logout" => "auth#logout"

    resources :chapters, :except => [:destroy, :update] do
      collection do
        get :finished
        get :unfinished
        get :weekpop
        get :mostpop
      end
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :chapters

  resources :users do
    resource :profile, :controller => "user_profiles"
  end

  resources :suggests

  resources :logs

  root 'chapters#index'

end

app/models/chapter.rb
class Chapter < ActiveRecord::Base

  validates_presence_of :topic, :content, :category_id

  has_ancestry :cache_depth => true
  belongs_to :user
  belongs_to :category

  mount_uploader :avatar, AvatarUploader

  scope :includes_more, -> { includes( :category, :user => :profile ) }

  scope :weekpop, -> { where( ["created_at >= ?", Time.now - 7.days ] ).order("view DESC").limit(10) }
  scope :finished, ->{ where( :finish => true ).order("id DESC") }
  scope :unfinished, ->{ where( :finish => false ).order("id DESC") }
  scope :begins, ->{ where( :ancestry => nil ).order("id DESC") }
  scope :mostpop, ->{ order("view DESC") }

  before_validation :setup_default_category, :on => :create

  def can_continue?
    self.depth < 2 && !self.finish
  end

  # TODO: add test  
  def image_urls
    self.content.scan(/src=["|'](.*?)["|']/).flatten
  end

  def self.search(params)
    
    collection = 
      if params[:category] && params[:category][:id].present?
        Category.find(params[:category][:id]).chapters
      else
        Chapter.all
      end

    collection = collection.where([ "topic like ?", "%#{params[:keyword]}%"]) if params[:keyword]
    # colelction = collection.where(xxxx) if params[:email]
    collection
  end

  protected

  def setup_default_category
    if self.parent
      self.category_id = self.parent.category_id
    end
  end

end

app/controllers/api_v1/chapters_controller.rb
class ApiV1::ChaptersController < ApiController

  before_action :authenticate_user!, :only => [:create]

  # GET /api/v1/chapters
  def index
    #@chapters = Chapter.page( params[:page] ).per(5)
    @chapters = Chapter.includes_more.order("id DESC")
  end

  # POST /api/v1/chapters
  def create
    # [CR] move to strong parameter, 
    # And remove user_id, it should become: @chapters = current_user.chapters.new
    @chapter = current_user.chapters.new(chapter_params)

    if @chapter.save
      render :json => { :id => @chapter.id, :message => "OK" }
    else
      render :json => { :message => "Invalid", :errors => @chapter.errors }, :status => 400
    end
  end

  # GET /api/v1/chapters/:id
  def show
    @chapter = Chapter.find(params[:id])
  end

  def finished
    @finish = Chapter.includes_more.finished
  end

  def unfinished
    @unfinished_chapters = Chapter.includes_more.unfinished
  end

  def weekpop
    @weekpop = Chapter.includes_more.weekpop
  end

  def mostpop
    @mostpop = Chapter.includes_more.mostpop
  end
  protected

  def chapter_params
    params.permit(:topic, :setting, :content, :finish, :category_id, :avatar, :avatar_cache, :remote_avatar_url, :parent_id )
  end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

  before_action :authenticate_user!, :except => [:index, :show]
  before_action :set_article, :only => [ :show, :edit, :update ]

  def index
    @weekpop = Chapter.includes_more.weekpop.search(params)
    @finish = Chapter.includes_more.finished.search(params)
    @unfinished = Chapter.includes_more.unfinished.search(params)
    @begins = Chapter.includes_more.begins.search(params)
    @mostpop = Chapter.includes_more.mostpop.search(params)

    @chapters = Chapter.search(params)

    sort_by = if %w[topic view].include?(params[:order])
      params[:order]
    else
      'id'
    end

    @chapters = @chapters.order(sort_by + " DESC")
  end
  
  def show
    @page_title = "故事里 - #{@chapter.topic}"

    unless cookies["view-chapter-#{@chapter.id}"]
      cookies["view-chapter-#{@chapter.id}"] = "viewed"
      @chapter.view = @chapter.view.to_i + 1
      @chapter.save!
    end
  end

  def new
    @chapter = Chapter.new(parent_id: params[:parent_id])
    @page_title = (@chapter.parent)? "故事里 - 接續故事 #{@chapter.parent.topic}" : "故事里 - 開創新的故事"
  end

  def create
    @chapter = current_user.chapters.new(chapter_params)

    if @chapter.save
      flash[:notice] = "成功新增故事"
      redirect_to chapter_path(@chapter)
    else
      render :action => :new
    end
  end

  def edit
    
  end

  def update
    @chapter.update(chapter_params)
    if @chapter.save
      flash[:notice] = "成功更新故事"
    redirect_to chapter_path(@chapter)
    else
      flash[:alert] = "故事標題或內容不可為空白"
      render :action => :edit
    end
  end

  private

  def set_article
    @chapter = Chapter.find(params[:id])
  end

  def chapter_params
    params.require(:chapter).permit(:topic, 
                                    :setting, 
                                    :content, 
                                    :finish, 
                                    :category_id, 
                                    :avatar, 
                                    :avatar_cache, 
                                    :remote_avatar_url, 
                                    :parent_id, 
                                    :category_id)
  end
end

app/helpers/api_v1/chapters_helper.rb
module ApiV1::ChaptersHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper

	def default_chapter_avatar(chapter)	   
    case chapter.category.try(:name)
      when "經典故事"
        image_tag "fairyTale/#{rand(1..16)}.jpg"
      when "結局改編"
        image_tag "reorganization/#{rand(1..14)}.jpg"
      when "時事創作"
        image_tag "currentEvent/#{rand(1..12)}.jpg"
    end
	end

end

app/views/chapters/_flow.html.erb
<h4>
  <%= d.category.name if d.category %>
</h4>
  <li>
    <%= link_to d.topic, chapter_path(d) %>
  </li>
  <% if d.has_children? %>
    <ol class="level2">
      <% d.children.each do |ch| %>
        <li>
          <%= link_to ch.topic, chapter_path(ch) %>
        </li>
          <% if ch.has_children? %>
            <ol class="level3">
              <% ch.children.each do |gc| %>
                <li>
                  <%= link_to gc.topic, chapter_path(gc) %>
                </li>
              <% end %>
            </ol>
          <% end %>
      <% end %>
    </ol>
  <% end %>

app/views/chapters/_masonry.html.erb
<div class="grid-item">
<%= link_to chapter_path(dd) do %>
  <% if dd.avatar.blank? %>
    <%= default_chapter_avatar(dd) %>
  <% else %>
    <%= image_tag dd.avatar.url %>
  <% end %>
  <h3><%= dd.topic %></h3>
  <h6><%= dd.category.try(:name) %></h6>
<% end %>
</div>

app/views/chapters/_sliders.html.erb
<div id="myCarousel" class="carousel slide" data-ride="carousel">
  <!-- Indicators -->
  <ol class="carousel-indicators">
    <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
    <li data-target="#myCarousel" data-slide-to="1"></li>
    <li data-target="#myCarousel" data-slide-to="2"></li>
  </ol>

  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">
    <div class="item active">
      <%= image_tag "UFO.jpg", :alt=>"協助外星人返鄉過年計畫" %>
    </div>

    <div class="item">
      <%= image_tag "im.jpg", :alt=>"協助外星人返鄉過年計畫" %>
    </div>

    <div class="item">
      <%= image_tag "alphastori.jpg", :alt=>"協助外星人返鄉過年計畫" %>
    </div>

  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

app/views/chapters/_writeChapter.html.erb
<% if @chapter.root? %>
  <h1>創造你的故事</h1>
<% else %>
  <h1>接續故事: <%= @chapter.parent.topic %></h1>
<% end %>

<%= form_for @chapter do |f| %>
  <%= f.hidden_field :parent_id %>

  <% if @chapter.root? %>
    <div class="form-group">
      <%= f.label :category_id, "故事分類："%>
      <%= f.select :category_id, Category.all.map{ |c| [c.name, c.id] } %>
    </div>
  <% end %>

  <div class="form_group">
    <%= f.label :avatar, "上傳故事封面圖片 檔案or連結" %>
    <%= f.file_field :avatar %>
    <%= f.text_field :remote_avatar_url %>
    <%= f.hidden_field :avatar_cache %>
  </div>

  <div class="form_group">
    <%= f.label :topic, "標題或故事大綱" %>
    <%= f.text_field :topic, :required => true, :class => "form-control", :placeholder => '命名也是很有趣der' , :autofocus => true%>
  </div>

  <% if @chapter.root? %>
    <div class="form_group">
      <%= f.label :setting, "故事設定" %>
      <%= f.text_field :setting, :class => "form-control", :placeholder => 'ex. 夜晚、台北、國家劇院' %>
    </div>
  <% end %>

  <div class="form_group">
      <%= f.label :content, "故事內容" %>
      <%= f.cktext_area :content, :required => true, :ckeditor => {:language => 'zh', :uiColor => 'lightgray', :toolbar => 'mini', :height => '300', :autoParagraph => true} %>
  </div>
<!-- #:ckeditor => {:language => 'zh', :uiColor => '#AADC6E', :toolbar => 'mini', :skin => 'kama', :extraPlugins => 'confighelper'} -->

<% if false %>
<!--   <div class="form_group">
    <%= f.label :content, "故事內容" %>
    <%= f.text_area :content, :required => true, :class => "form-control", :placeholder => '請盡情發揮，沒有人會阻止你' %>
  </div>
 -->
<% end %>

  <div class="form_group">
    <% if @chapter.depth == 2 %>
      <%= f.select :finish, [ ['結束故事', true] ] %>
    <% else %>
      <%= f.select :finish, [['可以接續', false], ['結束故事', true]] %>
    <% end %>
    <%= f.label :finish, "選擇故事是否完結！？" %>
  </div>

  <hr>

  <div class="form_group">
    <%#= f.submit "送出故事", :data => {:confirm => "你確定喔送出不能改喔！！"}, :class => 'btn btn-primary' %>
  </div>
<%# end %>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  預覽故事
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">預覽故事</h4>
      </div>
      <div class="modal-body">
        <% @chapter.ancestors.each do |p| %>

          <p><%= "前情提要：（故事第#{p.depth+1}層）" %></p>
          <p><%= "故事標題： #{p.topic}" %></p>
          <% if p.root? %>
          <p><%= "故事設定： #{p.try(:setting)}" %></p>
          <% end %>
          <p><%= image_tag p.avatar.thumb.url %></p>
          <p><%= simple_format p.content %></p>
          <hr>
        <% end %>
          <p>準備送出的新故事片段：</p>

          <div id="preview">...</div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "送出故事", :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>
<% end %>


<script>

$("[data-target='#myModal']").click(function(){
  var cke_data = CKEDITOR.instances.chapter_content.getData()
      topic = $("#chapter_topic")
      t = topic.val()
      setting = $("#chapter_setting")
      s = setting.val();

  $("#preview").html(
   "<p>標題：" + t + "</p>" +
   "<p>故事設定：" + s + "</p>" +
   "<p>內容：" + cke_data + "</p>"
  );
})

  $("#chapter_finish").select2({ width: "auto", minimumResultsForSearch: Infinity });
  $("#chapter_category_id").select2({ width: "auto", minimumResultsForSearch: Infinity });


</script>

app/views/chapters/edit.html.erb
<%= render partial:"writeChapter" %>

app/views/chapters/index.html.erb
<ul class="nav nav-tabs nav-justified" role="tablist">
  <li role="presentation"><a href="#weekpop" aria-controls="weekpop" role="tab" data-toggle="tab">一週熱門</a></li>
  <li role="presentation"><a href="#mostpop" aria-controls="mostpop" role="tab" data-toggle="tab">最受歡迎</a></li>
  <li role="presentation"><a href="#finished" aria-controls="finish" role="tab" data-toggle="tab">已完結的故事</a></li>
  <li role="presentation"><a href="#begins" aria-controls="begins" role="tab" data-toggle="tab">故事的開始</a></li>
  <li role="presentation"><a href="#unfinished" aria-controls="unfinished" role="tab" data-toggle="tab">等待接續的故事</a></li>
  <li role="presentation"><a href="#storyline" aria-controls="storyline" role="tab" data-toggle="tab">所有故事結構表</a></li>
  <li role="presentation"><a href="#crowdy" aria-controls="crowdy" role="tab" data-toggle="tab">crowdy</a></li>
</ul>

<div class="tab-content">
  <div role="tabpanel" class="tab-pane" id="weekpop">
    <h2 style="text-align: center">一週熱門</h2>
      <div class="grid" >
      <% @weekpop.each do |dd| %>
          <%= render :partial => 'masonry', :locals => { :dd => dd } %>
      <% end %>
      <div class="grid-item add" style="height: 65px; width: 390px"><%= link_to "我要開啟一段新的故事", new_chapter_path , :class => "btn btn-primary" %></div>
      </div>
  </div>

  <div role="tabpanel" class="tab-pane" id="mostpop">
    <table class="table table-striped">
        <h2 style="text-align: center">最受歡迎</h2>
        <tr>
          <th>圖示</th>
          <th>標題</th>
          <th>作者</th>
          <th>場景</th>
          <th>類別</th>
          <th>點閱</th>
          <th>層級</th>
          <th>完成</th>
        </tr>
          <% @mostpop.each do |c| %>
            <tr>
              <td class="table-image">
                <%= link_to chapter_path(c) do %>
                  <% if c.avatar.blank? %>
                    <%= default_chapter_avatar(c) %>
                  <% else %>
                    <%= image_tag c.avatar.url %>
                  <% end %>
                <% end %>
              </td>
              <td><%= link_to c.topic, chapter_path(c)%></td>
              <td><%= link_to c.user.try(:display_name), user_profile_path( c.user.id ) if c.user %></td>
              <td><%= c.setting %></td>
              <td><%= c.category.name if c.category %></td>
              <td><%= c.view %></td>
              <td><%= c.depth+1 %></td>
              <td><%= c.finish %></td>
            </tr>
          <% end %>
      </table>
  </div>

  <div role="tabpanel" class="tab-pane" id="finished">
    <h2 style="text-align: center">已完結的故事</h2>
    <div class="grid" >
    <% @finish.each do |dd| %>
        <%= render :partial => 'masonry', :locals => { :dd => dd } %>
    <% end %>
    <div class="grid-item add" style="height: 65px; width: 390px"><%= link_to "我要開啟一段新的故事", new_chapter_path , :class => "btn btn-primary" %></div>
    </div>
  </div>

  <div role="tabpanel" class="tab-pane" id="begins">
    <h2 style="text-align: center">故事的開始</h2>
    <div class="grid" >
      <% @begins.each do |dd| %>
        <%= render :partial => 'masonry', :locals => { :dd => dd } %>
      <% end %>
      <div class="grid-item add" style="height: 65px; width: 390px"><%= link_to "我要開啟一段新的故事", new_chapter_path , :class => "btn btn-primary" %></div>
      </div>
  </div>

  <div role="tabpanel" class="tab-pane" id="unfinished">
    <h2 style="text-align: center">等待接續的故事</h2>
    <div class="grid" >
      <% @unfinished.each do |dd| %>
        <%= render :partial => 'masonry', :locals => { :dd => dd } %>
      <% end %>
      <div class="grid-item add" style="height: 65px; width: 390px"><%= link_to "我要開啟一段新的故事", new_chapter_path , :class => "btn btn-primary" %></div>
    </div>
  </div>

  <div role="tabpanel" class="storyline tab-pane" id="storyline">
  <h2 style="text-align: center">所有故事結構表</h2>
    <div class="element">
      <ol class="level1">
      <% @chapters.roots.each do |d| %>
        <%= render :partial => 'flow', :locals => { :d => d } %>
      <% end %>
      </ol>
    </div>
  </div>

  <div role="tabpanel" class="tab-pane" id="crowdy">
    <div class="col-md-4">
   <!-- FB fan page -->
      <div class="fb-page" data-href="https://www.facebook.com/crowdy.space/" data-tabs="timeline" data-small-header="false" data-adapt-container-width="true" data-hide-cover="false" data-show-facepile="true">
        <div class="fb-xfbml-parse-ignore">
            <blockquote cite="https://www.facebook.com/crowdy.space/"><a href="https://www.facebook.com/crowdy.space/">Crowdy-群眾共同創作平台</a></blockquote>
        </div>
      </div>
    <!-- FB fan page -->
    </div>
    <div class="col-md-7 col-md-offset-1">
      <div class="slider">
        <%= render :partial => 'sliders' %>
      </div>
    </div>
  </div>

</div>

<script>
  $(window).load(function () {

    $('.nav-tabs a[href="#weekpop"]').tab('show');

    $('.grid').masonry({
      itemSelector: '.grid-item',
      fitWidth: true
    });

    var $container = $('.grid');
    $container.imagesLoaded(function() {
      $container.masonry({
          gutter: 10,
          transitionDuration: '0.8s'
      });
    });
  });

  $('.nav-tabs a').click(function (e) {
    e.preventDefault()
    $(this).tab('show');

    $('.grid').masonry({
      itemSelector: '.grid-item',
      fitWidth: true
    });
  })
</script>

app/views/chapters/new.html.erb
<% if @chapter.root? %>
  <h1>創造你的故事</h1>
<% else %>
  <h1>接續故事: <%= @chapter.parent.topic %></h1>
<% end %>

<%= form_for @chapter, :url => chapters_path do |f| %>
  <%= f.hidden_field :parent_id %>

  <% if @chapter.root? %>
    <div class="form-group">
      <%= f.label :category_id, "故事分類："%>
      <%= f.select :category_id, Category.all.map{ |c| [c.name, c.id] } %>
    </div>
  <% end %>

  <div class="form_group">
    <%= f.label :avatar, "上傳故事封面圖片 檔案or連結" %>
    <%= f.file_field :avatar %>
    <%= f.text_field :remote_avatar_url %>
    <%= f.hidden_field :avatar_cache %>
  </div>

  <div class="form_group">
    <%= f.label :topic, "標題或故事大綱" %>
    <%= f.text_field :topic, :required => true, :class => "form-control", :placeholder => '命名也是很有趣der' , :autofocus => true%>
  </div>

  <% if @chapter.root? %>
    <div class="form_group">
      <%= f.label :setting, "故事設定" %>
      <%= f.text_field :setting, :class => "form-control", :placeholder => 'ex. 夜晚、台北、國家劇院' %>
    </div>
  <% end %>

  <div class="form_group">
      <%= f.label :content, "故事內容" %>
      <%= f.cktext_area :content, :required => true, :ckeditor => {:language => 'zh', :uiColor => 'lightgray', :toolbar => 'mini', :height => '300', :autoParagraph => true} %>
  </div>


<!-- #:ckeditor => {:language => 'zh', :uiColor => '#AADC6E', :toolbar => 'mini', :skin => 'kama', :extraPlugins => 'confighelper'} -->
<% if false %>
<!--   <div class="form_group">
    <%= f.label :content, "故事內容" %>
    <%= f.text_area :content, :required => true, :class => "form-control", :placeholder => '請盡情發揮，沒有人會阻止你' %>
  </div>
 -->
<% end %>

  <div class="form_group">
    <% if @chapter.depth == 2 %>
      <%= f.select :finish, [ ['結束故事', true] ] %>
    <% else %>
      <%= f.select :finish, [['可以接續', false], ['結束故事', true]] %>
    <% end %>
    <%= f.label :finish, "選擇故事是否完結！？" %>
  </div>
  
  

  <hr>

  <div class="form_group">
    <%#= f.submit "送出故事", :data => {:confirm => "你確定喔送出不能改喔！！"}, :class => 'btn btn-primary' %>
  </div>
<%# end %>

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
  預覽故事
</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">預覽故事-送出即無法更改喔</h4>
      </div>
      <div class="modal-body">
        <% @chapter.ancestors.each do |p| %> 

          <p><%= "前情提要：（故事第#{p.depth+1}層）" %></p>
          <p><%= "故事標題： #{p.topic}" %></p>
          <% if p.root? %> 
          <p><%= "故事設定： #{p.try(:setting)}" %></p>
          <% end %>
          <p>故事內容：<%= simple_format p.content %></p>
          <hr>
        <% end %>
          <p>準備送出的新故事片段：</p>  
        
          <div id="preview">...</div>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit "送出故事", :data => {:confirm => "你確定喔送出不能改喔！！"}, :class => 'btn btn-primary' %>
      </div>
    </div>
  </div>
</div>
<% end %>


<script>

$("[data-target='#myModal']").click(function(){
  var cke_data = CKEDITOR.instances.chapter_content.getData()
      topic = $("#chapter_topic")
      t = topic.val()
      setting = $("#chapter_setting")
      s = setting.val();

  $("#preview").html(
   "<p>標題：" + t + "</p>" +
   "<p>故事設定：" + s + "</p>" +
   "<p>內容：" + cke_data + "</p>"
  );
})

  $("#chapter_finish").select2({ width: "auto", minimumResultsForSearch: Infinity });
  $("#chapter_category_id").select2({ width: "auto", minimumResultsForSearch: Infinity });
  

</script>

app/views/chapters/show.html.erb
<div class="chapter-show">
  <div class="chapter-head">
    <span>
      <h1>
        <%= @chapter.topic %>
      </h1>
    </span>
    <span>
      by <%= link_to @chapter.user.display_name, user_profile_path(@chapter.user) if @chapter.user.present? %>
    </span>

    <span>
      at <%= @chapter.created_at.to_formatted_s(:short) %>
    </span>
  </div>
<!-- fb-like -->
  <div class="fb-like" data-href="<%= chapter_url(@chapter) %>" data-width="500px" data-layout="standard" data-action="like" data-show-faces="true" data-share="true" colorscheme = "dark"></div>
<!-- fb-like -->

  <% if @chapter.parent %>
      <p style="text-align: right; border-radius: 50%"><%= link_to "回到上一層故事： #{@chapter.parent.topic}", chapter_path(@chapter.parent) , :class=>"btn btn-success"%></p>
    <% end %>

  <% if @chapter.parent %>
    <% @chapter.ancestors.each do |p| %>
      <div class="story-btn">
        <a class="btn btn-warning" role="button" data-toggle="collapse" href="#collapseExample<%= p.depth %>" aria-expanded="false" aria-controls="collapseExample<%= p.depth %>">
      回顧一下故事 <%= "#{p.category.name if p.category} 第#{p.depth+1}" %>層：
        </a>
      </div>
      <div class="collapse" id="collapseExample<%= p.depth %>">
        <div class="well">
          <span>
            <h3>
              <%= p.topic %>
            </h3>
          </span>
          <span>
            by <%= link_to p.user.display_name, user_profile_path(p.user) if p.user.present? %>
          </span>
          <span>
            at <%= p.created_at.to_formatted_s(:short) %>
          </span>
          <% if p.root? %>
          <div class="chapter-setting">
            <span>故事設定：</span>
            <span><%= p.setting %></span>
          </div>
          <% end %>
          <div class="chapter-img">
            <span>
              <% if p.avatar.thumb.url %>
                <%= image_tag p.avatar.thumb.url, :class => "chapter-cover" %>
              <% end %>
            </span>
          </div>
          <div class="chapter-content">
            <p>
              <%= simple_format p.content %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
<% end %>
  <hr>
    <% if @chapter.root? %>
      <div class="chapter-setting">
        <span>故事設定：</span>
        <span><%= @chapter.setting %></span>
      </div>
    <% end %>

    <% if @chapter.avatar.url %>
      <div class="chapter-img">
        <span>
          <%= image_tag @chapter.avatar.url, :class => "chapter-cover" %>
        </span>
      </div>
    <% end %>

      <div class="chapter-content">
        <span>
          <%= simple_format @chapter.content %>
        </span>
      </div>
      <div>
        <% if current_user == @chapter.user %>
          <%= link_to "修改",edit_chapter_path(@chapter), title:"請注意，如果內容有重大變更，請用新的故事接續，確保其他共創故事的延續性:)", :data => {:confirm => "請注意，如果內容有重大變更，請用新的故事接續，確保其他共創故事的延續性:)"}, class:"btn btn-info" %>
        <% end %>
      </div>
      <div>
        <% if @chapter.can_continue? %>
          <%= link_to "我要接續這段故事", new_chapter_path(:parent_id => @chapter.id, :category_id => @chapter.category_id) , :class => "btn btn-primary"%>
        <% end %>
      </div>
  <hr>

  <% if @chapter.has_children? %>
    <% @chapter.children.each do |c| %>
      <p style="text-align: right; border-radius: 50%"><%= link_to "觀賞下一層的故事： #{c.topic}", chapter_path(c) , :class=>"btn btn-success"%></p>
    <% end %>
  <% end %>
  <div class="fb-comments" data-href="<%= chapter_url(@chapter) %>" data-width="500px" data-numposts="5" colorscheme = "dark" data-order-by="reverse_time"></div>
</div>