config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do

    resources :profiles, :only => [:show, :update], :controller => "user_profiles"

    post "login" => "auth#login"
    post "logout" => "auth#logout"

    resources :chapters, :except => [:destroy, :update] do
      collection do
        get :finished
        get :unfinished
        get :weekpop
        get :mostpop
      end
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :chapters

  resources :users do
    resource :profile, :controller => "user_profiles"
  end

  resources :suggests

  resources :logs

  root 'chapters#index'

end

app/models/log.rb
class Log < ActiveRecord::Base

	validates_presence_of :topic, :content
	belongs_to :user

end

app/controllers/logs_controller.rb
class LogsController < ApplicationController

	before_action :authenticate_user!, :except => [:index]

	before_action :set_log, :only => [:update, :destroy]
	before_action :set_logs, :only => [:index, :create, :update]

	def index
		if params[:log_id]
			@log = Log.find(params[:log_id])
		else
			@log = Log.new
		end
	end

	def create
		@log = current_user.logs.new(log_params)
		if @log.save
			flash[:notice] = "新增成功"
			redirect_to logs_path
		else
			flash[:alert] = "新增失敗"
			render :index
		end
	end

	def update
		@log.update(log_params)
		if @log.save
			flash[:notice] = "更新成功"
			redirect_to logs_path
		else
			flash[:alert] = "更新失敗"
			render :index
		end
	end

	def destroy
		@log.destroy
		flash[:alert] = "記錄已刪除"
		redirect_to logs_path
	end

	private

	def log_params
		params.require(:log).permit(:topic, :content, :logtime)
	end

	def set_log
		@log = Log.find(params[:id])
	end

	def set_logs
		@logs = Log.all.order("logtime DESC")
	end

end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/logs/index.html.erb
<div class="change-logs">
	<h1>Change Logs</h1>
	<!-- fb-like -->
	  <div class="fb-like" data-href="<%= logs_url %>" data-width="500px" data-layout="standard" data-action="like" data-show-faces="true" data-share="true" colorscheme = "dark"></div>
	<!-- fb-like -->
	<% if current_user && current_user.admin? %>
		<%= form_for @log do |f| %>
			
			<div class="form-group">
			  <%= f.label :logtime, "日期："%>
			  <%= f.date_select :logtime %>
			</div>

			<div class="form-group">
			  <%= f.label :topic, "標題："%>
			  <%= f.text_field :topic %>
			</div>

			<div class="form-group">
			  <%= f.label :content, "項目內容："%>
			  <%= f.text_area :content, size: "70x5" %>
			</div>

			<%= f.submit "送出", class:"btn btn-primary" %>
		<% end %>
	<% end %>	

	<table class="table table-striped">
	  <tr>
	  	<th>標題</th>
	    <th>日期</th>
	    <th>發佈者</th>
	    <th>內容</th>
	    <th>操作</th>
	  </tr>
	  <% @logs.each do |l| %>
	  <tr>
	    <td><%= l.topic %></td>
	    <td><%= l.logtime %></td>
	    <td><%= link_to l.user.display_name, user_profile_path( l.user.id ) %></td>
	    <td><%= simple_format l.content %></td>
	    <td>
				<% if current_user && current_user.admin? %>
	      	<%= link_to "修改",logs_path(log_id:l), class:"btn btn-success" %>
	      	<%= link_to "刪除",log_path(l), :method => :delete, :data => { :confirm => "Are you sure?" }, class:"btn btn-danger" %>
	    	<% end %>
	    </td>
	  </tr>
	  <% end %>
	</table>
	<div class="fb-comments" data-href="<%= logs_url %>" data-width="500px" data-numposts="5" colorscheme = "dark" data-order-by="reverse_time"></div>
</div>