config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do

    resources :profiles, :only => [:show, :update], :controller => "user_profiles"

    post "login" => "auth#login"
    post "logout" => "auth#logout"

    resources :chapters, :except => [:destroy, :update] do
      collection do
        get :finished
        get :unfinished
        get :weekpop
        get :mostpop
      end
    end
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :chapters

  resources :users do
    resource :profile, :controller => "user_profiles"
  end

  resources :suggests

  resources :logs

  root 'chapters#index'

end

app/views/layouts/_about.html.erb
<div class="modal fade bs-about-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content" >
      <div id="header-button">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
          </button>
          <h4 class="modal-title" id="myLargeModalLabel">關於我們：</h4>
        </div>
        <h4></h4>
        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;這是一個共同用文字和圖片創作的平台，我們認為由多人共同創作的故事，可以激發彼此的想像力，因著無法預測其他人會怎麼接續故事的發展，而使得每一個故事都充滿著無限可能和驚喜；我們希望每一個人在這裡找到靈感、發揮創意，更藉由大家的想像力，讓故事變成我們生活中的一趟奇幻之旅！</p>
        <hr>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_how.html.erb
<div class="modal fade bs-how-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content" >
      <div id="header-button">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
          </button>
          <h4 class="modal-title" id="myLargeModalLabel">使用教學：</h4>
        </div>
        
        <h4>1.發起故事：</h4>
        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;你可以寫一個故事的起頭，讓其他人來發揮和接續你的故事。<br>
        你可以選擇經典故事的改編（像是白雪公主或是屈原跳河的故事等）、結局改編（我可能不會愛你中，又青姐真的該選擇大仁哥嗎？）、時事創作（王如玄哭哭說：我一輩子沒有做過公主，網友神答：因為你是巫婆...）</p>
        <h4>2.接續故事：</h4>
        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;你可以瀏覽平台中，感到有興趣的故事，並選擇接續別人的故事，或是為故事寫下令人意想不到的結局。
        不過，一個故事限制三個人可以接龍，最多可以連結兩次（所以是三層的故事），要搶要快！</p>
        <hr>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_privacy.html.erb
<div class="modal fade bs-example-modal-lg" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg">
    <div class="modal-content" >
      <div id="header-button">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
          <h4 class="modal-title" id="myLargeModalLabel">隱私權政策：</h4>
        </div>

        <h4>宣言：</h4>

        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;本站是由「Crowdy 群眾共同創作平台」所經營，以下簡稱Crowdy共創平台，為了能讓各位顧客知道Crowdy共創平台非常重視個人資料的保護，針對消費者與個人資料之蒐集和運用，依中華民國「電腦處理個人資料保護法」及本隱私權保護聲明，Crowdy共創平台已加強相關之保護措施。Crowdy共創平台以下列的對外聲明中，說明對於線上使用者個人資料的使用方式、使用範圍、使用方法等相關事項，請您務必詳細閱讀以下各項內容後再進行登錄註冊，當您登錄註冊完成，即視為您已閱讀、了解並同意接受本隱私保護聲明的內容。</p>

        <h4>個人資料蒐集及使用：</h4>

        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;當您瀏覽Crowdy共創平台時，不會主動要求輸入個人資料。當您完成參加其他活動時，才會要求您登錄個人資料，以便完成相關服務。訂閱電子報只需提供Email帳號，使用者想取消訂閱，可隨時至本網站取消訂閱。 當您在Crowdy共創平台主動註冊成為會員後，您所輸入的資料，僅供Crowdy共創平台提供服務或活動設計參考使用。凡未經您主動註冊所產生的資料，例如使用者機器的 IP 位址、使用時間、使用的瀏覽器、瀏覽及點選紀錄等資料，本網站僅對全體使用者行為總和進行分析，並不會對個別使用者進行分析。Crowdy共創平台會自動記錄您在網站內的瀏覽，這些資料僅作為流量分析和網路行為調查，便於改善網站服務品質。除事先說明或依台灣法律規定外，Crowdy共創平台不會擅自將您的個人資料提供給第三者或作為其他目的之用。</p>

        <h4>使用者註冊說明：</h4>

        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Crowdy共創平台所取得的個人資料，都僅供Crowdy共創平台內部、依照原說明目的和規範使用，除非事先說明、或依照相關法律規定，否則本網站不會將您的個人資訊透露第三方、或移作其他目的使用。</p>

        <h4>自我保護措施：</h4>

        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;請勿在網路上公開透露您個人資料，因該資料有可能會被他人蒐集和使用，特別是在網路上公開的發言場合，如聊天室、留言版，更應避免發表個人身份、密碼或電子郵件等相關個人資料。如果您與他人共用電腦或使用公共電腦，請記得關閉瀏覽器，以防他人看到上述資料取得您帳號的方法。</p>

        <h4>隱私權保護政策之修訂：</h4>

        <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Crowdy共創平台保留更改本聲明各項內容之權利，我們將於網站同一位置公告更改之聲明外，不另外對會員進行個別通知。</p>
        
        <hr>
        
        <p>若您對本隱私權保護政策有任何問題，請寫信與本平台聯繫。<%= mail_to "dylanmail0203@gmail.com", "故事里-開發部",
         subject: "Crowdy-stori 故事里信件" %></p>

        <hr>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @page_title || 'Stori - 故事里' %></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=0.8, maximum-scale=2.0, user-scalable=yes">
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <%= favicon_link_tag 'favicon.ico' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
  </head>
  <body>

<div id="fb-root"></div>

<script>
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/zh_TW/sdk.js#xfbml=1&version=v2.5&appId=<%= facebook_app_id %>";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
</script>


    <div class="container">
      <div class="row">
        <div class="col-md-12">
          <nav class="navbar navbar-inverse navbar-fixed-top">
            <div class="container-fluid">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <%= link_to root_path, :title => "首頁", :class=>"navbar-brand" do %>
                  <%= image_tag "stori200.png","alt"=>"Brand" %>
                <% end %>
              </div>

              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav">
                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" title="來看看我們的理念">
                        <span class="fa-stack fa-lg">
                          <i class="fa fa-square-o fa-stack-2x"></i>
                          <i class="fa fa-info fa-stack-1x"></i>
                        </span>
                        <span>關於我們</span>
                      <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                      <li>
                        <%= link_to "", 'data-toggle'=>"modal", "data-target"=>".bs-about-modal-lg", :title => "來看看我們的理念" do %>
                          <span class="fa-stack fa-lg">
                            <i class="fa fa-square-o fa-stack-2x"></i>
                            <i class="fa fa-info fa-stack-1x"></i>
                          </span>
                          <span>關於我們</span>
                        <% end %>
                      </li>
                      <li>
                        <%= link_to "", 'data-toggle'=>"modal", "data-target"=>".bs-how-modal-lg", :title => "點這裡來看怎麼玩兒" do %>
                          <span class="fa-stack fa-lg">
                            <i class="fa fa-square-o fa-stack-2x"></i>
                            <i class="fa fa-users fa-stack-1x"></i>
                          </span>
                          <span>HOW TO PLAY!?</span>
                        <% end %>
                      </li>
                      <li>
                        <%= link_to "", 'data-toggle'=>"modal", "data-target"=>".bs-example-modal-lg", :title => "我們會保護你的隱私" do %>
                          <span class="fa-stack fa-lg">
                            <i class="fa fa-square-o fa-stack-2x"></i>
                            <i class="fa fa-lock fa-stack-1x"></i>
                          </span>
                          <span>隱私權政策</span>
                        <% end %>
                      </li>
                    </ul>
                  </li>
                  <li>
                    <%= link_to "", :title => "iosApp上架審核中", :class=>"ios" do %>
                      <span class="fa-stack fa-lg">
                        <i class="fa fa-square-o fa-stack-2x"></i>
                        <i class="fa fa-mobile fa-stack-1x"></i>
                      </span>
                      <span>iOS App</span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to suggests_path, :title => "大家可以建議想要的功能還有錯誤回報謝謝" do %>
                      <span class="fa-stack fa-lg">
                        <i class="fa fa-square-o fa-stack-2x"></i>
                        <i class="fa fa-commenting-o fa-stack-1x"></i>
                      </span>
                      <span>建議我們</span>
                    <% end %>
                  </li>
                  <li>
                    <%= link_to logs_path, :title => "顧名思義更新日誌就是更新的記錄" do %>
                      <span class="fa-stack fa-lg">
                        <i class="fa fa-square-o fa-stack-2x"></i>
                        <i class="fa fa-list-alt fa-stack-1x"></i>
                      </span>
                      <span>更新日誌</span>
                    <% end %>
                  </li>
                </ul>

                <ul class="nav navbar-nav">

                  <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                      <% if current_user %>
                      <span class="fa-stack fa-lg">
                      <i class="fa fa-square-o fa-stack-2x"></i>
                      <i class="fa fa-cogs fa-stack-1x"></i>
                      </span>
                      <!-- 使用者設定 -->
                      <% else %>
                        <span class="fa-stack fa-lg">
                          <i class="fa fa-square-o fa-stack-2x"></i>
                          <i class="fa fa-cogs fa-stack-1x"></i>
                        </span>
                        登入選項
                      <% end %>
                      <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu">
                      <% if current_user %>
                      <li>
                        <%= link_to user_profile_path( current_user.id ), :title => "個人資料" do %>
                          <span class="fa-stack fa-lg">
                            <i class="fa fa-square-o fa-stack-2x"></i>
                            <i class="fa fa-user fa-stack-1x"></i>
                          </span>
                          <span><%= "Hi! #{current_user.display_name}" %></span>
                        <% end %></li>
                      <li>
                        <%= link_to destroy_user_session_path, :method => :delete, :title => "如果使用公共的電腦記得離開前要登出喔" do %>
                          <span class="fa-stack fa-lg">
                            <i class="fa fa-square-o fa-stack-2x"></i>
                            <i class="fa fa-sign-out fa-stack-1x"></i>
                          </span>
                          <span>登出</span>
                        <% end %>
                      </li>
                      <li>
                        <%= link_to edit_registration_path(:user), :title => "想換換密碼按這裡" do %>
                          <span class="fa-stack fa-lg">
                            <i class="fa fa-square-o fa-stack-2x"></i>
                            <i class="fa fa-key fa-stack-1x"></i>
                          </span>
                          <span>修改密碼</span>
                        <% end %>
                      </li>
                      <% else %>
                      <li>
                        <%= link_to new_registration_path(:user), :title => "用email來註冊後加入我們" do %>
                          <span class="fa-stack fa-lg">
                            <i class="fa fa-square-o fa-stack-2x"></i>
                            <i class="fa fa-rocket fa-stack-1x"></i>
                          </span>
                          <span>註冊</span>
                        <% end %>
                      </li>
                      <li>
                        <%= link_to new_session_path(:user), :title => "用你上次註冊的email來登入" do %>
                          <span class="fa-stack fa-lg">
                            <i class="fa fa-square-o fa-stack-2x"></i>
                            <i class="fa fa-sign-in fa-stack-1x"></i>
                          </span>
                          <span>登入</span>
                        <% end %>
                      </li>
                      <li>
                        <%= link_to user_facebook_omniauth_authorize_path(:facebook), :title => "用非死不可登入又快又方便喔" do %>
                          <span class="fa-stack fa-lg">
                            <i class="fa fa-square-o fa-stack-2x"></i>
                            <i class="fa fa-facebook fa-stack-1x"></i>
                          </span>
                          <span>登入 Facebook</span>
                        <% end %>
                      </li>
                      <% end %>
                    </ul>
                  </li>
                </ul>
                <form class="navbar-form navbar-right" role="search">
                  <div class="form-group">
                  <%= collection_select( :category, :id, Category.all, :id, :name,{:include_blank => '選擇故事類別or不分類'}) %>
                    <%= text_field_tag "keyword","", :class=>"form-control", :placeholder=>"Search..." %>
                  </div>
                  <button type="submit" class="btn btn-default">搜尋</button>
                </form>
              </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
          </nav>
          <hr>
          <% if flash[:notice].present? %>
            <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
          <%end%>

          <% if flash[:alert].present? %>
            <div class="alert alert-danger" role="alert"><%= flash[:alert] %></div>
          <%end%>

          <%= yield %>

        </div>
      </div>
    </div>
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-71871619-1', 'auto');
      ga('send', 'pageview');
    </script>
  </body>
</html>

<%= render :partial => "layouts/privacy" %>
<%= render :partial => "layouts/about" %>
<%= render :partial => "layouts/how" %>